name: Bug report
description: Report something that is not working as expected
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting! Please fill this out so I can reproduce the issue."

  - type: input
    id: aseprite_version
    attributes:
      label: Aseprite version
      placeholder: "e.g. 1.3.9"
    validations:
      required: true

  - type: input
    id: extension_version
    attributes:
      label: Extension version
      placeholder: "e.g. v1.0.5 (or 'latest release')"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) Open file... 2) File > Export Slices as PNGs... 3) ..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "What happened instead?"
    validations:
      required: true

  - type: checkboxes
    id: context
    attributes:
      label: Context (if relevant)
      options:
        - label: Sprite has multiple frames
        - label: Slices overlap
        - label: There are duplicate slice names
        - label: Hidden layers are involved
        - label: I am exporting from a non-first frame

  - type: textarea
    id: logs
    attributes:
      label: Error message / console output (if any)
      description: "If Aseprite shows an error dialog or console output, paste it here."
      render: shell
    validations:
      required: false

  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: "If possible, attach screenshots or a sample .aseprite file (remove private content)."
    validations:
      required: false